[BOL-393] 임시멤버 기록 연동 시 프로필 설정 팝업 사라지지 않음 이슈
YAPP-Github/onboard-aos pull request #160
Opened 2023-09-17 10:21 UTC by ckrudals

### Reference
- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-393)

### 참고 사항

P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)

2023-09-17 12:36 UTC, prk4224 requested changes
코멘트만 확인해주세요 !

2023-09-17 12:36 UTC, prk4224 commented on presentation/src/main/java/com/yapp/bol/presentation/view/group/join/GroupJoinFragment.kt
>                          handleSuccessJoinGroup()
p2. 여기 닉네임 값들어가야해요 
```
handleSuccessJoinGroup(nickname)
```

2023-09-18 11:39 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/group/join/GroupJoinFragment.kt
>                          handleSuccessJoinGroup()
@prk4224 https://github.com/YAPP-Github/onboard-aos/pull/160/commits/7af77ef4c2dd4162d28ce473f3d694194403fe51 완료

2023-09-18 13:20 UTC, prk4224 approved these changes
수정 내용 확인했습니다 !

2023-09-18 14:45 UTC, eunjjungg approved these changes

2023-09-18 14:47 UTC, merged