[BOL-54]  매치 기능에서 게임 선택 화면 구현
YAPP-Github/onboard-aos pull request #36
Opened 2023-06-13 09:40 UTC by prk4224

### Reference
- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-54)

### 참고 사항

P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)

2023-06-15 13:27 UTC, ckrudals requested changes

2023-06-15 13:27 UTC, ckrudals commented on domain/src/main/java/com/yapp/bol/domain/repository/Repository.kt
p3 : API 가 2개이상 나왔으니, 각각의 Repository 로 만들어도 좋을 것 같아요. LoginRepository, GroupRepository?

그리고 파라미터에 `trailing comma` 가 빠진것 같은데 확인 부탁드려요!

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/utils/CheckedEmptyValue.kt
> +val isEmptyValue: (String?) -> Boolean = { value ->
p2 : 프로퍼티 이름을 봤을 때 `String.isNullEmpty()` 의 기능과 혼동될 가능성이 있어 보여요, 좀 더 구체적인 이름으로 짓는게 좋을 것 같아요, 어떤 상황, 어떤 기능을 담는지 포함되면 좋을것 같네요.

p3 : 프로퍼티에는  많은 기능이 있을 것이라 생각하기 어려워요 (이펙티브 코틀린) 따라서 함수로 만드는 것은 어떨까요?

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/utils/CheckedEmptyValue.kt
> +     value?.matches(regex) ?: false
p3 : 정렬 해주세요!

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/utils/Constant.kt
p3 : `Constant` 의 class 에 모든 부분의 상수를 추가하는 것보단, 각각의 화면, 기능에 대해 class 를 추가하는 것은 어떨가요?
지금같은 경우에는 GameConstant, Constant 로 나눌 수 있겠네요.

후에 상수가 많아질수록 관리하기도 어렵고, 각각 으로 나누면 어디에 추가할지 명확해 질 것 같아요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/utils/SetImage.kt
> +import android.net.Uri
p1 : 안쓰는 Import 같아요, 제거해주세요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/utils/SetImage.kt
> +fun ImageView.setImage(imageUri: String) {
p3 : `setImage` 보단 `loadImage` 로 변경하는 것은 어떨가요? `setImage` 느낌은 Android drawable 에 있는 image 를 넣어줄 것 같은데, `loadImage` 는 외부에 이미지를 불러온다는 느낌이 강해 `loadImage` 가 더 적합할 것 같아요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/group/NewGroupCompleteActivity.kt
정렬 한번 해주세요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/group/NewGroupViewModel.kt
> +    val isCompleteButtonActivation
p3 : viewModel 의 프로퍼티 이름에 `Button` 이 포함되어야 할 이유가 있을가요? 의미 전달이 불필요 할 것 같고, `isCompleteActivation` 만으로도 의미 전달이 충분할 것 같아요!

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/MatchViewModel.kt
> +class MatchViewModel @Inject constructor() : ViewModel() {
p3 : 후에 hilt 를 사용될 것 이라 생각하고, `@Inject constructor()` 를 추가해줬다면 `@HiltViewModel` annotation 도 추가해 주세요!

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/MatchViewModel.kt
> +    private val _toolBarTitle = MutableLiveData(GAME_RESULT_RECORD)
이 부분도 위의 커멘트와 동일하게 `toolBar` 의 이름이 불필요 한 것 같아요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectAdapter.kt
> +    private val gameClickListener: (String) -> Unit
👍, trailing comma 추가해주세요

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectAdapter.kt
> +        }
p3 :` getItem(position)` 이 non-null 이라 holder.bind(getItem(position)) 로도 충분하지 않나요?

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectAdapter.kt
> +            //binding.ivProductImage.setImage(item.imageUrl)
p3 : pr 올리실 때 특별한 이유가 없으면 코드 주석을 제거해주세요. 리뷰어가 이 코드에 대한 주석을 단 이유에 대해 불필요한 시간을 소비하지 않을 수 있어요 😀

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectFragment.kt
> +    private val recyclerAdapter = GameSelectAdapter { gameName ->
p3 : `recyclerAdapter` 이름보단 `gameSelectAdapter` 이름이 어떤가요? 어떤 기능이 담고있는지 정보가 있으면 좋을 것 같아요.

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectFragment.kt
> +        )
p3 : navigation component 의 기능중 `safeArgs` 를 사용하면 손쉽게 데이터를 전달할 수 있어요

2023-06-15 13:27 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectFragment.kt
> +    }
p5 : 
```suggestion
   ): View = FragmentGameSeleteBinding.inflate(inflater, container, false).apply {
        _binding = this
    }.root
```
개인적으로 요렇게 하는것을 선호합니다

2023-06-15 23:22 UTC, prk4224 commented
@ckrudals 좋은 피드백 감사해요. 빨리 코드를 짜다보니 세세한 부분을 신경 못썼네요. 웬만한 부분은 다 반영했고, Toolbar 나 Button 같은 경우 제거 한다면 Title을 을 어디 사용하지 ? 무슨 완료가 활성화 된다는 거야 ? 이런 의문점이 들수 있다고 생각해서 명확하게 붙이는 것을 선호하는 편입니다. Constant 나 navigation 같은 경우도 아직 논의 전 단계하고 생각해서 정석적인 방법을 택했고 추후 논의 하면 좋을거 같아요. 또 전 이정도 규모에서 그렇게 까지 Repository를 나누는게 맞는지 의문점이 들어서 추후 논의해보고 수정하도록 해도 나머지 내용 확인해주세요 ~

2023-06-15 23:24 UTC, prk4224 commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/game_select/GameSelectFragment.kt
> +    }
오 괜찮은 방법이네요 !  근데 개인적으로는 가독성이 조금 떨어지는 느낌...

2023-06-16 04:53 UTC, ckrudals commented
@prk4224 리뷰가 논의할 내용이 있거나, 수정이 되었으면 커멘트를 달아주면 좋을 것 같아요. 커밋을 보기전 커멘트의 상태를 보고 해결/미해결 의 상태를 알 수 있으면 시간 단축이 될 것 같습니다. 😀

2023-06-16 05:29 UTC, prk4224 commented
@ckrudals 제네럴하게 수정한 부분이 많아서 한번에 했는데, 이제 다음부턴 다 같이 커밋 링크까지 올리는 걸로해요 ~~ 확인 했으면 승인 부탁드려요 ~

2023-06-16 05:30 UTC, prk4224 commented
@ckrudals 참고로 제가 언급한 부분뺴고는 수정 다 헀습니다 ~

2023-06-16 08:07 UTC, eunjjungg approved these changes
고생 많으셨습니다! lgtm 😎

2023-06-16 08:07 UTC, eunjjungg commented on presentation/src/main/java/com/yapp/bol/presentation/utils/CheckedEmptyValue.kt
> +val isInputTextValid: (String?) -> Boolean = { value ->
p5: 이 부분 혹시 프로퍼티로 변경하신 이유가 있으신가요? 💁 크게 상관은 없는것 같기는 한데 제가 최근에 이펙티브 코틀린 스터디를 해서 이 [부분](https://onlyfor-me-blog.tistory.com/520)과 관련이 있을까 싶어 코멘트 남깁니다. 사소한 부분이라 반영은 안 해주셔도 됩니다!

2023-06-16 08:07 UTC, eunjjungg commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +        _binding = FragmentMemberSelectBinding.inflate(inflater, container, false)
~~p4: 이 부분 binding을 lazy로 선언하면 checkNotNull과 초기화까지 한 번에 가능할 것 같아요! 혹시 다른 사유가 있어서 이렇게 하신거라면 패스해주세요! 🙏😊~~

제가 잘못 리뷰했네요...하하 죄송합니다~!

2023-06-16 10:32 UTC, merged