[BOL-53] 매치 화면에서 플레이어 선택 화면 구현
YAPP-Github/onboard-aos pull request #38
Opened 2023-06-16 16:34 UTC by prk4224

### Reference
- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-53)

### 참고 사항

P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)

2023-06-19 07:20 UTC, eunjjungg approved these changes
스타일 수정에서 구현까지 고생 정말 많으셨습니다~!! ktlint가 참 엄격하네요..하핳... 🥹

2023-06-19 07:20 UTC, eunjjungg commented on domain/src/main/java/com/yapp/bol/domain/usecase/login/MatchUseCase.kt
> +package com.yapp.bol.domain.usecase.login
p4: package가 login으로 되어있는데 이 부분은 추후에 수정해주시나요?~ 🫠

2023-06-19 07:20 UTC, eunjjungg commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectAdapter.kt
> +                return oldItem.name == newItem.name
p5: 이건 그냥 개인적으로 보다가 아! 그렇구나 한 부분인데 ㅋㅋㅋ 어 왜 id 값으로 비교를 안 하시고 name으로 비교하셨지 생각했습니다..! 근데 생각해보니까 저희 이름이 고유값이라 비교해도 되는군요..!! 🧐👍

2023-06-19 07:20 UTC, eunjjungg commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +    }
p5: 저도 이와 같은 기능이 제 부분에 필요해 구현하였는데..! 이렇게 구현할수도 있군요~! 잘 보고 갑니다..ㅎㅎ! 👍

2023-06-19 07:20 UTC, eunjjungg commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +        if (activity == null && activity?.currentFocus == null) return
p4: 궁금한 점인데..! 여기 `activity == null && activity?.currentFocus == null`에서 전자가 null이면 후자는 당연히 null이라고 생각하는데 혹시 제가 잘못 알고 있는 걸까요?! 잘못 안 부분이라면 말씀해주십셔! 🫡

2023-06-19 07:40 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +        if (activity == null && activity?.currentFocus == null) return
은정님 말씀처럼 `activity == null` 요 조건은 불필요한 것 같네요. `activity?.currentFocus == null` 이 조건만 있어도 충분할 것 같습니다.

2023-06-19 09:36 UTC, prk4224 commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectAdapter.kt
> +                return oldItem.name == newItem.name
악 처음에 MemberItem 만들 때 id 값을 안 넣어서 name 으로 했는데 추후 id로 안 바꿨네요...

2023-06-19 09:41 UTC, prk4224 commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +        if (activity == null && activity?.currentFocus == null) return
그러네요 !  복붙 코드 그대로 사용했네요...하하 수정할게요 😵

2023-06-23 14:38 UTC, ckrudals requested changes

2023-06-23 14:38 UTC, ckrudals commented on data/src/main/java/com/yapp/bol/data/model/group/GameDTO.kt
> +    val img: String,
p3 : `@serializedname` 을 사용해서 좀더 구체적인 이름을 사용하면 좋을것 같아요 ~

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/login/NaverTestActivity.kt
> +            if (it.accessToken == Constant.EMPTY_STRING) return@collectWithLifecycle
p3 : 전의 리뷰에서도 한번 말했지만 kotlin collection 중 `.isEmpty()` 를 사용하면 개발자가 상수를 따로 지정하지 않아도 원하는 동작을 할 것 같아요 ~

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/MatchViewModel.kt
> +    private val _members = MutableLiveData<List<MemberItem>>(listOf())
p5 : 단순한 궁금증인데 Flow 대신 LiveData 를 사용하시는 이유가 있으실까요?~

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/MatchViewModel.kt
> +    val members = _members
```suggestion
    private val _members = MutableLiveData<List<MemberItem>>(listOf())
    val members = _members.asLiveData()
```
외부에 보여질 때 immutable 하게 만들기 위해 asLiveData() 로 감싸야해요!
참고 [link](https://velog.io/@changhee09/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-LiveData#:~:text=%EC%A0%9C%EA%B1%B0%ED%95%A0%20%EC%88%98%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.-,LiveData%20%EB%A7%8C%EB%93%A4%EA%B8%B0,-LiveData%EB%8A%94%20%EC%9C%84%EC%97%90%EC%84%9C)

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/MatchViewModel.kt
> +        }
p3 : 아직 API 연결하기 전 이신거죠 ?

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectAdapter.kt
> +        }
p3 : `getItem(position)` 이 non-null 인데 let 으로 감쌀 이유가 있어요 ??

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectAdapter.kt
> +    private val memberDeleteClickListener: (MemberItem) -> Unit,
p3 : `onMemberDelete` 요정도로 만 지어도 외부에 의미 전달이 충분히 될 것 같아요.

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
>      private val binding get() = checkNotNull(_binding)
p3 : `checkNotNull` 이 필요한 검증이에요 ?

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
>          val gameName = arguments?.getString(GAME_NAME) ?: ""
p2 : 전에도 말했지만, viewModel 에서 `savedstatehandle` 를 통해 값을 받아올 수 있어요~ view 에는 코드 가 적으면 적을수록 좋으니 이관하면 좋을 것 같아요!

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +
p3 : keybord 내리는게 다른 화면에서도 공통적으로 사용되어 [utils 에 object](https://github.com/YAPP-Github/22nd-Android-Team-2-Android/pull/48/files#diff-14d9139dcc823d7c7131555bb4eac8a38dde2a4b416f66aa077393704376acb6:~:text=object-,Keyboard,-%7B) 로 만들었습니다 ! 이 pr 이 머지되면 적용하면 좋을 것 같아요 !

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +        setClickListener()
p3 : 함수 추상화 레벨을 통일하면 좋을 것 같아요. 위의 기능들도 함수로 만들면 좋을 것 같아요. 참고 [link](https://javabom.tistory.com/146)

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
> +    private fun setViewModelObserve() {
p3 : `subscribeObseravles` 정도의 이름이면 될 것 같아요. set 은 외부의 데이터를 내부의 데이터에 설정한다는 느낌인데, viewModel 의 value 를 구독(subscribe) 하고 있으니까요!

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MembersAdapter.kt
> +class MembersAdapter(
p4 : `MemberListAdapter` 정도가 좋을 것 같아요. 멤버 리스트를 `Members` 보단 `MemberList` 을 일반적으로 많이 사용하니 `Members` 는 어색한 느낌이 드네요.

2023-06-23 14:38 UTC, ckrudals commented on presentation/src/main/res/mipmap-hdpi/ic_member_level.png
p3 : drawable 이 아닌 mipmap 으로 하신 이유가 있어요 ?

2023-06-24 03:16 UTC, ckrudals approved these changes

2023-06-24 03:30 UTC, merged