feat: setting-base
YAPP-Github/onboard-aos pull request #7
Opened 2023-05-25 14:24 UTC by eunjjungg

### Reference
- [Notion Ticket](https://www.notion.so/yapp-workspace/AOS-project-setting-2-a923406454c24134ac2dcc259534171a?pvs=4)

### 참고 사항

P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)

2023-05-25 16:25 UTC, ckrudals requested changes

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/AndroidManifest.xml
> +                <category android:name="android.intent.category.LAUNCHER" />
```suggestion
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
```

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +    }
p4 : [kotlin 공식문서](https://kotlinlang.org/docs/coding-conventions.html#class-layout) 공식문서 보면 companion object 는 class 의 맨하단에 위치하길 권장하고 있네요.

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/DataSourceImplModule.kt
> +    @Provides
```suggestion
class DataSourceImplModule {

    @Provides
```

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +            .writeTimeout(15, TimeUnit.SECONDS)
p4 : 하드코딩 보단 상수로 만드시는 것은 어떤가요?

2023-05-25 16:25 UTC, ckrudals commented on app/build.gradle.kts
> +    compileSdk = 32
p3 : Android 관련된 버전도  `Dependenceis.kt` 에 정의 하는 것은 어떨까요?

2023-05-25 16:25 UTC, ckrudals commented on app/build.gradle.kts
> +    // implementation(com.yapp.bol.DaggerHilt.DAGGER_HILT_VIEW_MODEL)
p3 : 이 `dependency` 만 주석처리 하신 이유는 무엇인가요?

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +                .addHeader("Content-Type", "application/json")
p4 : 아직 API 스펙이 확정되지 않아 주석처리 한거죠? todo 로 남겨주면 후에 확인할 때 더 편할 것 같습니다.

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    }
p4 : `provideBaseUrl` 를 사용하는 경우가 생기나요? 
`provideBaseUrl` 를 피라미터로 주입하는 경우와 상수인 `BASE_URL` 를 사용하는 경우와 각각 어떤 차이가 있나요?

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/RepositoryModule.kt
> +        )
p5 : 한줄로 처리 가능한 함수는 single Function 으로 만들면 가독성이 좋아집니다. 
```suggestion
    ): MockRepository = MockRepositoryImpl(mockDataSourceImpl)
```
p5 : 한줄로 처리 가능한 함수는 [single-expression-function](https://kotlinlang.org/docs/functions.html#single-expression-functions) 으로 만들면 가독성이 좋아집니다. 
아래 부분은 single-expression-function 으로 만드셨던데, 기준이 있을가요?

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    fun provideOAuthApiService(retrofit: Retrofit): OAuthApi {
p3 : 함수이름을 `OAuth` 보단 `Login` 이름을 붙히는 것은 어떨까요? `OAuth` 는 프로토콜일 뿐이고 실제로 수행하는 기능은 Login 인 것 같아요 ~

2023-05-25 16:25 UTC, ckrudals commented on build.gradle
> +//    }
p3 : 주석처리 하신 이유가 무엇인가요?

2023-05-25 16:25 UTC, ckrudals commented on build.gradle
> +    id 'com.android.library' version '7.3.1' apply false
p3 : `Dependencies.kt` 에 있는 상수로 값을 변경해 주세요.

2023-05-25 16:25 UTC, ckrudals commented on buildSrc/src/main/java/com/yapp/bol/Dependencies.kt
> +// ktlint-disable filename
p3 : 이 주석이 필요한 이유가 무엇인가요? 아래 `KtLint` dependency 가 있는 것으로 봐서는 불필요해 보이는데요.

2023-05-25 16:25 UTC, ckrudals commented on data/src/main/java/com/yapp/bol/data/utils/Utils.kt
> +    const val BASE_URL = "http://3.39.205.168:8080/v1/"
p3 : @eunjjungg @prk4224 서버 URL 를 외부(git) 에 노출하면 안될 것 같은데, 어떻게 처리하면 좋을까요?

2023-05-25 16:25 UTC, ckrudals commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
p5 : `safeApiCall` 으로 에러 핸들링하는 것을 처음봐서, 몇가지 의문점이 있습니다. 
1. 현재 `RemoteErrorEmitter` 를 `DataStore` , `Repository`, `Usecase`, `ViewModel` 에 각각 활용하고 있는데 각각 활용하는게 너무 번거로울 것 같다는 생각이드네요, `runCaching` 과 비교했을 때 어떠한 이점이 있나요?
2. `ViewModel` 에 이 인터페이스를 사용하고 있는데 그러면 viewModel 에서는 하나의 API 밖에 호출하지 못하는 건가요?

2023-05-25 16:25 UTC, ckrudals commented on app/src/main/AndroidManifest.xml
> +
```suggestion
        android:name="com.yapp.bol.app.di.App"
```

2023-05-25 16:25 UTC, ckrudals commented on presentation/src/main/res/layout/activity_main.xml
> +        android:id="@+id/btnKakao"
p5 : id naming 에 관련된 규칙 논의도 필요해 보이네요, 더미로 만든 거지면 resource 는 snake case 로 사용하는게 좋아보여요!
[android-style-guide](https://github.com/PRNDcompany/android-style-guide)

2023-05-26 00:21 UTC, prk4224 requested changes
확인 완료. 코멘트 확인 부탁드려요 ~

2023-05-26 00:21 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/DataSourceImplModule.kt
> +class DataSourceImplModule {
p3. 
생각해보니 DataSourceImplModule 이름이 조금 이상한거 같아요. 
그냥 DataSourceModulde 로 해도 괜찮지 않을까요 ?

2023-05-26 00:21 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +        appInterceptor: com.yapp.bol.app.di.NetworkModule.AppInterceptor,
p2.
Interceptor 도 Provide 로 만들면 코드가 깔끔해질거 같아요.

2023-05-26 00:21 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    class AppInterceptor @Inject constructor() : Interceptor {
p3. 
@Inject constructor() 이게 왜 필요하나요 ? 🤔

2023-05-26 00:21 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/UseCaseModule.kt
> +class UseCaseModule {
p4.
저희 UseCase 도 interface 로 만들기로 했나요 ?

2023-05-26 00:22 UTC, prk4224 commented on data/src/main/java/com/yapp/bol/data/utils/Utils.kt
> +    const val BASE_URL = "http://3.39.205.168:8080/v1/"
local properties 나 암호화 방법이 있을거 같은데 전 전자를 택하는 편입니다 ~

2023-05-26 01:29 UTC, EvergreenTree97 approved these changes
저도 슥 리뷰하고 갑니다..!

2023-05-26 01:29 UTC, EvergreenTree97 approved these changes
저도 슥 리뷰하고 갑니다..!

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/build.gradle.kts
> +    compileSdk = 32
```kotlin
object Apps {
    const val minSdk = 23
    const val targetSdk = 33
    const val compileSdk = 33
    const val jvmTarget = "11"
    const val versionCode = 1
    const val versionName = "1.0.0"
    val targetCompat = JavaVersion.VERSION_1_8
    val sourceCompat = JavaVersion.VERSION_1_8
}
```
경민님 말씀하신 대로 Dependencies에 같이 작성하거나, Applications.kt 요런 파일 하나 만들어서 관리 하는 편이, kts의 장점을 좀 더 살릴 수 있을 것 같아요!

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +        private lateinit var application: App
어떤 용도로 작성하신 코드인지 궁금합니다!!😉

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/src/main/java/com/yapp/bol/app/di/DataSourceImplModule.kt
> +        oauthApi: OAuthApi,
DatasourceImpl
```OAuthApi```는 `DatasourceImpl`의 @Inject에서 주입 받을 수 있는 형태로 만들어져요!
그래서 @Binds 메서드를 사용하는게 hilt generate 파일을덜 생성할 수 있을 것 같습니다 ㅎㅎ
| https://kotlinworld.com/106 이해하기 좋아용

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    class AppInterceptor @Inject constructor() : Interceptor {
개발자가 제어할 수 있는 인터페이스의 구현체의 경우 생성자에 @Inject를 명시한다면 @Provides와 같이 주입 가능한 형태로 제공해줄 수 있어요!

하지만 현재 경우는 위에서 재홍님이 말씀해주신 것 처럼 @Provides로 만드는 방법이 좀 더 직관적일 것 같네요!

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/src/main/java/com/yapp/bol/app/di/RepositoryModule.kt
> +        )
마찬가지로 @Binds 를 사용하는게 코드 생성을 줄일 수 있을 것 같네요~~

2023-05-26 01:29 UTC, EvergreenTree97 commented on app/src/main/java/com/yapp/bol/app/di/UseCaseModule.kt
> +    fun provideKakaoLoginUseCase(repository: MockRepository): KakaoLoginUseCase = KakaoLoginUseCase(repository)
`Usecase`를 Interface 한번 거쳐 제공해주지 않는 형태라면, `@Inject`를 통해 이미 주입될 수 있는 형태로 만들어지기 때문에 `UseCaseModule`은 불필요한 파일이 될 것 같습니다!

2023-05-26 04:32 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +            .writeTimeout(15, TimeUnit.SECONDS)
저는 이 부분은 ms 단위가 아니고 초 단위여서 오히려 상수화 시키는게 더 가독성에 좋지 않을 것 같다고 생각했습니다. 뒤에 Time의 단위도 써있어서 오히려 상수화 시키지 않는게 더 나을 것 같은데 어떻게 생각하시나요?! 🧐 이 object의 하나 함수에만 사용하고 있어 필요성을 느끼지 못한 것 같습니다..!

2023-05-26 04:48 UTC, eunjjungg commented on app/build.gradle.kts
> +    compileSdk = 32
아..! 그렇군여!! 다들 말씀해주신 덕분에 좀 더 활용할 방법을 알게 된 것 같습니다. 감사합니다!! 🙇

2023-05-26 07:54 UTC, prk4224 commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
@ckrudals 
runCaching  사용하면 어떤 에러가 발생했는지 어디서 판단하나요 ?
2번 질문은 이해를 못하겠어요..인터페이스 사용안하고 있고 사용하고 있더라도 하나의 API 밖에 호출하지 못한다는게 이해가 안돼요 자세히 설명해주세요 !

2023-05-26 07:54 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    class AppInterceptor @Inject constructor() : Interceptor {
@EvergreenTree97 오호 새로운 사실이네요. 그래서 HiltViewModel을 사용할때 Inject를 사용안하면 에러가 나는거군요..

2023-05-26 07:54 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +            .writeTimeout(15, TimeUnit.SECONDS)
@eunjjungg 가독성도 가독성인데, 다른 사람이 읽었을 때 저 10에 대한 의미를 모르기 때문에 ? 보통 상수화를 많이 하는걸로 알고있어요 ~ 위와 상황을 예시로 들면 앞의 함수명이 때문에 왜 사용하는지는 알겠는데, 왜 10으로 설정했지 ? 그런 의문이 들 거 같아요 🤔

2023-05-26 08:31 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +            .writeTimeout(15, TimeUnit.SECONDS)
> @eunjjungg 가독성도 가독성인데, 다른 사람이 읽었을 때 저 10에 대한 의미를 모르기 때문에 ? 보통 상수화를 많이 하는걸로 알고있어요 ~ 위와 상황을 예시로 들면 앞의 함수명이 때문에 왜 사용하는지는 알겠는데, 왜 10으로 설정했지 ? 그런 의문이 들 거 같아요 🤔

아하! 저는 근데 함수명, 뒤의 TimeUnit이 다 정해져 있어서 필요 없다고 생각하긴 했는데.. 그럴수도 있겠군요. 그렇다면 추천해주실만한 변수명이 있을까요? 저는 당장 `readTimeOutInterval` 이런 변수밖에 생각이 안 드네요 🥹

2023-05-26 08:51 UTC, eunjjungg commented on app/build.gradle.kts
> +    // implementation(com.yapp.bol.DaggerHilt.DAGGER_HILT_VIEW_MODEL)
이거는 이 [문제](https://salmonpack.tistory.com/34) 때문에 제가 잠시 제거해본다고 주석 처리 했었는데 미처 제거를 못했네요..! 제거하겠습니다~

2023-05-26 09:11 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    }
``` kotlin
@Singleton
@Provides
fun provideRetrofitInstance(
    baseUrl: String,
    okHttpClient: OkHttpClient,
    gsonConverterFactory: GsonConverterFactory,
): Retrofit {
    return Retrofit.Builder()
        .baseUrl(baseUrl)
        .client(okHttpClient)
        .addConverterFactory(gsonConverterFactory)
        .build()
}
```

사실 별다른 차이는 없는 것 같은데 `Retrofit.Builder()` 를 할 때 매개변수로 사용되는 것들을 다 주입받고 싶다는 생각에서 이렇게 작성한 것 같아요..!

2023-05-26 09:52 UTC, ipf-kmcha commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    }
기능적으로 큰 차이가 없다면 
Provides 함수를 만들어 주입하는 것보다, 상수로 만들어 사용하는 것이 비용적인 측면에서 더 이점이 있어요.

따라서 요건 상수로 만들어 사용하는 것이 좋을 것 같아요.

2023-05-26 09:56 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    }
기능적으로 큰 차이가 없다면
Provides 함수를 만들어 주입하는 것보다 상수로 바로 사용하는 것이 비용적인 측면에서 더 이점이 있는 것 같아요.

따라서 따로 함수로 만들지 않고 상수로만들어 사용하는것은 어떨까요?

2023-05-26 10:30 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/RepositoryModule.kt
> +        )
두 분 다 좋은 리뷰 감사합니다! 

> 아래 부분은 single-expression-function 으로 만드셨던데, 기준이 있을가요?

single expression function 안 쓴 이유가 어렴풋이 기억나는데.. ㅋㅋㅋ 제 기억에 저기서 다른 코드 찍어보다가.. 삭제는 했는데 미처 single expression function으로 돌릴 생각은 안 했던 것 같아요. 앞으론 좀 꼼꼼하게 처리해볼게요! 

> 마찬가지로 https://github.com/BINDS 를 사용하는게 코드 생성을 줄일 수 있을 것 같네요~~

제가 Hilt 사용이 익숙치 않아서 @Binds를 어디서 사용해야 할지 헤매고 있었는데 이런 거였군요..! 감사합니다!! 주신 링크도 학습하는데 큰 도움이 되었습니다! 👍🙇

2023-05-26 10:35 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    fun provideOAuthApiService(retrofit: Retrofit): OAuthApi {
넵! 수정하겠습니다~! 😀

2023-05-26 12:29 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/NetworkModule.kt
> +    class AppInterceptor @Inject constructor() : Interceptor {
좋은 리뷰 감사합니다!! 🙇 해당 부분도 수정하겠습니다!!

2023-05-26 12:35 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/UseCaseModule.kt
> +class UseCaseModule {
> p4. 저희 UseCase 도 interface 로 만들기로 했나요 ?

아뇨.. 처음에 interface 없이 만들기로 했었고 실제로 그렇게 했는데 대체 이 파일을 왜 만들었는지 모르겠네요.. 🥲🥲🥲🥲🥲 말씀해주셔서 감사합니다.. 덕분에 바로 제거해버렸어여!

2023-05-26 12:40 UTC, eunjjungg commented on buildSrc/src/main/java/com/yapp/bol/Dependencies.kt
> +// ktlint-disable filename
이 [이유](https://stackoverflow.com/questions/57395287/how-to-disable-filename-in-ktlint) 때문에 작성했습니다!

2023-05-26 12:41 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/UseCaseModule.kt
> +    fun provideKakaoLoginUseCase(repository: MockRepository): KakaoLoginUseCase = KakaoLoginUseCase(repository)
감사합니다..! 의미 없는 Hilt 사용을 너무 많이 한 것 같네요...! 학습을 더 해야겠다는 계기가 되었습니다! 리뷰 감사합니다!! 🙇‍♀️

2023-05-26 12:48 UTC, eunjjungg commented on build.gradle
> +//    }
multi module로 변경하면서 제거하기 전에 잠시 주석처리 해뒀는데 제가 까먹고 제거를 안 했네요~ 반영해서 수정하겠습니다!

2023-05-28 14:53 UTC, comforest commented on buildSrc/src/main/java/com/yapp/bol/Dependencies.kt
> +// ktlint-disable filename
제가 알기로 이거 클래스 한개일 경우에는 클래스명과 파일명을 일치 시켜야하지만
클래스가 여러개 선언된 파일일 경우엔 에러 발생 안하는걸로 알아요

2023-05-29 00:43 UTC, prk4224 approved these changes
확인 완료 ! 머지 해도 될거 같네요

2023-05-29 00:43 UTC, prk4224 commented on app/src/main/java/com/yapp/bol/app/di/RepositoryModule.kt
> +abstract class RepositoryModule {
p5. 개인적은 스타일인데 bind 만 하는 경우에 추상 클래스 보단 인터페이스로 하는 편인거 같아요. 추상 클래스의 경우에는 provide 와 bind를 함께 사용하는 경우에 사용하구요. 성능상 차이는 없지만 뭔가 구분이 잘되는 느낌 ? 인거 같아요. 🙌

2023-05-29 08:35 UTC, ckrudals approved these changes

2023-05-29 08:35 UTC, ckrudals commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +        fun getInstance(): App = application
p3 : 구두로 말했지만 까먹을까봐 한번더 남깁니다! 후에 사용이 안될 것 같으면 제거해주세요.

2023-05-29 08:35 UTC, ckrudals commented on build.gradle.kts
> +    id("com.android.library") version "7.3.1" apply false
p3 : Applications.kt 에 있는 상수로 변경해주세요.

2023-05-29 08:35 UTC, ckrudals commented on data/src/main/AndroidManifest.xml
> +</manifest>
```suggestion
<manifest xmlns:android="http://schemas.android.com/apk/res/android"/>
```
p5 : 정말 사소하지만 불편해서..

2023-05-29 08:35 UTC, ckrudals commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
@prk4224 `MainViewModel` 코드를 보면 `RemoteErrorEmitter` 이 인터페이스를 상속받고 있는데 viewModel 관점에서 보면 어떤 API 의 에러핸들링인지 알 수 없지 않나요? viewModel 에서 호출하고 있는 API 가 여려개라면..

제가 잘 못 알수있으니 참고 부탁드려요.🙇‍♀️

2023-05-29 08:44 UTC, jsh-me commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +        fun getInstance(): App = application
p2; application context 를 app 파일에서 직접 받으면서 사용하는 케이스는 클래스 간 의존성을 더 강화하는 방안인 것 같습니다. 지금 빌딩하고 있는 프로젝트에서는 application 을 직접 받아야 케이스는 발생할 수 없을 것 같기도 하고 ㅎㅎ hilt 에서 application context 를 제공하고 있으니 그것을 사용하는건 어떨까 의견드립니다 :)

2023-05-29 11:08 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +        private lateinit var application: App
안 그래도 리뷰를 받으니 저도 제가 이 코드를 대체 무슨 생각으로 짠건지.. 모르겠어서 그동안 고민했습니다.. 이전에 hilt를 도입하기 전에 작성했었던 프로젝트들을 보니 applicationContext를 사용하기 위해 작성했었더라구요..! hilt를 사용함에도 불구하고 당연히 필요할거라고 생각하고 작성한 코드 같습니다..! 🥹 리뷰 덕분에 많이 배워가게 되었습니다 감사합니다!

2023-05-29 11:11 UTC, eunjjungg commented on app/src/main/java/com/yapp/bol/app/di/App.kt
> +        fun getInstance(): App = application
> p2; application context 를 app 파일에서 직접 받으면서 사용하는 케이스는 클래스 간 의존성을 더 강화하는 방안인 것 같습니다. 지금 빌딩하고 있는 프로젝트에서는 application 을 직접 받아야 케이스는 발생할 수 없을 것 같기도 하고 ㅎㅎ hilt 에서 application context 를 제공하고 있으니 그것을 사용하는건 어떨까 의견드립니다 :)

@jsh-me 세희님 감사합니다..! 사실 오늘 회의 시간에도 비슷한 얘기를 나눴고, 제거해야겠다는 생각은 들었는데 그럼에도 명확하게 정리가 되지 않는 느낌이었습니다. 하지만 설명해주신 덕분에 왜 사용할 필요가 없는지와 단점에 대해 좀 더 명확하게 알 수 있게 되었습니다..! 감사합니다 🙇‍♀️🥹

2023-05-29 12:25 UTC, prk4224 approved these changes

2023-05-29 12:25 UTC, prk4224 commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
@ckrudals 아 인터페이스 상속 받고 있구나...근데 API 여러개라 하더라도 ErrorType 있는거 보면 데이터 레이어에서 에러 판단에서 어떤에러인지 보내주고 그 ErrorType에 따라 ViewModel 이 이벤트 처리하는 로직같은데요 ? API 가 여려개든 한개든 상관없지 않을까요 ? 
그리고 보니까 RemoteErrorEmitter 를 DataStore , Repository, Usecase, ViewModel 에서 활용하고 있는게 아니라 SafeApiCall 부분에서 에러 판단해서 ViewModel까지 흘려보내는 구조 같아요 . 사실 이건도 클린아키텍처 샘플보고 따라친 코드라고 하니까 구현하면서 저희가 바꾸면서 해도 될거 같아요 ~

2023-05-29 12:39 UTC, islandparadise14 commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
<img width="438" alt="스크린샷 2023-05-29 오후 9 28 37" src="https://github.com/YAPP-Github/22nd-Android-Team-2-Android/assets/39309953/c284cf55-8c8e-4457-9f24-a65aac9b5a53">

지금 usecase를 excute 할때 
"RemoteErrorEmitter를 상속받은 뷰모델" 을 넘겨서 구분이 안된다는것 같아요
이렇게 되면 결과적으로 하나의 callback 이 여러 usecase 에 대응해야하기 때문에
usecase 마다의 에러를 별도로 정의해야하는데 비슷한 에러도 usecase 가 다르면 새로 에러타입을 따야될걸로 보이네요

ex) usecase1 과 usecase2 의 네트워크 에러가 전부 viewModel 의 onError로 들어옴 만약 둘중 하나의 네트워크 에러는 동작에 별 영향을 안받아서 무시해도 되는 상황이며 usecase1의 네트워크 에러와 usecase2의 네트워크 에러를 구별하기 위해서 networkError1, networkError2 가 필요하게 됨

제가볼때 간단히 해결할 수 있는 방법은
excute 할때 익명 object 를 만들어서 callback을 받은다면 해결될거 같은데요
한번 고려해봐주세요

밑의 방법으로 하면 usecase 마다 에러대응이 될것 같아요

```
kakaoLoginUseCase.excute(object: RemoteErrorEmitter {
    override fun onError ~~
    override fun onError ~~
}, "SUCCESSid")
```

2023-05-29 12:53 UTC, merged

2023-05-29 23:19 UTC, eunjjungg commented on domain/src/main/java/com/yapp/bol/domain/utils/RemoteErrorEmitter.kt
> +}
@islandparadise14 정현님! 너무 리뷰 감사합니다..! 덕분에 anonymous class 만드는 방식을.. 다른 라이브러리 사용할 때 사용했음에도 불구하고 제대로 이해하지 못하고 아무 생각 없이 복붙해서 사용했다는 것을 알게 됐습니다....... 😂 정말.. 이렇게 사용할수 있는데..! 이 부분에 대해서도 공부해보겠습니다. 리뷰 감사합니다! 🙇‍♀️